/*
 * setting
 *
 * Copyright (c) 2000 - 2011 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#ifndef __SETTING_STORAGE_STRING_H__
#define __SETTING_STORAGE_STRING_H__


#define STORAGEUG_MAX_STR_LEN 64

#define STORAGEUG_STR_FAIL "IDS_CST_POP_FAILED"
#define STORAGEUG_STR_OK "IDS_ST_BUTTON_OK"
#define STORAGEUG_STR_CANCEL "IDS_ST_BUTTON_CANCEL_ABB"
#define STORAGEUG_STR_BACK "IDS_ST_BUTTON_BACK"
#define STORAGEUG_STR_DELETE "IDS_ST_BODY_DELETE"
#define STORAGEUG_STR_BT "IDS_ST_BODY_BLUETOOTH"
#define STORAGEUG_STR_NFC "IDS_ST_BODY_NFC"
#define STORAGEUG_STR_DELETE_Q "IDS_ST_POP_DELETE_Q"
#define STORAGEUG_STR_NO_FILES "IDS_VR_POP_NO_FILES"

#define STORAGEUG_STR_STORAGE "IDS_ST_BODY_STORAGE"
#define STORAGEUG_STR_INTERNAL_STORAGE "IDS_ST_BODY_DEVICE_MEMORY"
#define STORAGEUG_STR_USED "IDS_ST_BODY_USED"

#define STORAGEUG_STR_TOTAL "IDS_ST_BODY_TOTAL_SPACE"
#define STORAGEUG_STR_SYS_MEM "IDS_ST_BODY_SYSTEM_MEMORY"
#define STORAGEUG_STR_APPS "IDS_ST_BODY_APPLICATIONS"
#define STORAGEUG_STR_PICS "IDS_ST_BODY_PICTURES_VIDEOS"
#define STORAGEUG_STR_AUDIO "IDS_ST_HEADER_AUDIO"
#define STORAGEUG_STR_MISCES "IDS_ST_BODY_MISCELLANEOUS_FILES"
#define STORAGEUG_STR_CACHE "IDS_ST_TMBODY_CACHE"
#define STORAGEUG_STR_AVAIL "IDS_ST_BODY_AVAILABLE"

#define STORAGEUG_STR_WAIT "IDS_ST_SK2_PLEASE_WAIT"

#define STORAGEUG_STR_DEF_STORAGE "IDS_ST_BODY_DEFAULT_STORAGE"

#define STORAGEUG_STR_SD_CARD "IDS_ST_BODY_SD_CARD"
#define STORAGEUG_STR_MOUNT_SD "IDS_ST_BODY_MOUNT_SD_CARD"
#define STORAGEUG_STR_UNMOUNT_SD "IDS_ST_BODY_UNMOUNT_SD_CARD"
#define STORAGEUG_STR_FORMAT_SD "IDS_ST_BODY_FORMAT_SD_CARD"
#define STORAGEUG_STR_INSERT "IDS_ST_BODY_INSERT_SD_CARD"
#define STORAGEUG_STR_AVAIL_SPACE "IDS_ST_BODY_AVAILABLE_SPACE"

#define STORAGEUG_STR_USB "IDS_ST_BODY_USB_OTG_STORAGE"
#define STORAGEUG_STR_MOUNT_USB "IDS_ST_BODY_MOUNT_USB_OTG_STORAGE"
#define STORAGEUG_STR_UNMOUNT_USB "IDS_ST_BODY_UNMOUNT_USB_OTG_STORAGE"
#define STORAGEUG_STR_FORMAT_USB "IDS_ST_BODY_FORMAT_USB_OTG_STORAGE"
#define STORAGEUG_STR_FORMAT_END "IDS_MF_POP_FORMAT_COMPLETED"

#define STORAGEUG_STR_SD_UNMOUNT_POPUP_MSG \
	"IDS_ST_BODY_UNMOUNTING_THE_SD_CARD_WILL_STOP_SOME_APPLICATIONS_FROM_F"\
	"UNCTIONING_UNTIL_YOU_MOUNT_THE_SD_CARD_AGAIN_MSG"
#define STORAGEUG_STR_FORMAT_MSG \
	"IDS_ST_BODY_THIS_ACTION_WILL_ERASE_THE_SD_CARD_IN_THE_PHONE_YOU_WILL_"\
	"LOSE_ALL_DATA_ON_THE_CARD_E"
#define STORAGEUG_STR_FORMAT_USE_MSG \
	"IDS_ST_BODY_THE_SD_CARD_IS_CURRENTLY_IN_USE_THIS_ACTION_WILL_ERASE_AL"\
	"L_DATA_ON_THE_SD_CARD_INCLUDING_THE_DATA_THAT_IS_CURRENTLY_BEING_USED"
#define STORAGEUG_STR_FORMAT_SECOND_Q \
	"IDS_ST_BODY_FORMATTING_SD_CARD_WILL_DELETE_ALL_DATA_DATA_CANNOT_BE_RE"\
	"COVERED_CONTINUE_Q"
#define STORAGEUG_STR_FORMATTING_SD "IDS_COM_BODY_FORMATTING_SD_CARD_ING"
#define STORAGEUG_STR_UNMOUNTING_SD "IDS_ST_POP_UNMOUNTING_SD_CARD_ING_ABB"

#define STORAGEUG_STR_USB_UNMOUNT_POPUP_MSG \
	"IDS_ST_POP_UNMOUNTING_USB_OTG_STORAGE_WILL_STOP_SOME_APPLICATIONS_MSG"
#define STORAGEUG_STR_UNMOUNTING "IDS_ST_POP_UNMOUNTING_ING_ABB"
#define STORAGEUG_STR_FORMATTING "IDS_ST_POP_FORMATTING_ING"
#define STORAGEUG_STR_USB_FORMAT_Q \
	"IDS_ST_BODY_FORMATTING_USB_OTG_STORAGE_WILL_DELETE_ALL_DATA_DATA_CANN"\
	"OT_BE_RECOVERED_CONTINUE_Q"
#define STORAGEUG_STR_USB_FORMAT_SECOND_Q \
	"IDS_ST_POP_FORMATTING_WILL_ERASE_ALL_DATA_FORMAT_Q"

#define STORAGEUG_STR_KB "IDS_ST_BODY_KB"
#define STORAGEUG_STR_MB "IDS_ST_BODY_MB"
#define STORAGEUG_STR_GB "IDS_ST_BODY_GB"

/* For default view */
#define STORAGEUG_STR_SHARED_CONTENTS "IDS_ST_HEADER_SHARED_CONTENT"
#define STORAGEUG_STR_WIFI "IDS_ST_HEADER_WI_FI_DIRECT"
#define STORAGEUG_STR_DOWNLOAD "IDS_ST_BODY_DOWNLOAD"
#define STORAGEUG_STR_APP "IDS_ST_BODY_APPLICATION"
#define STORAGEUG_STR_INSTALLED_APP_H "IDS_ST_HEADER_INSTALLED_APPLICATIONS"
#define STORAGEUG_STR_INSTALLED_APP_B "IDS_ST_BODY_INSTALLED_APPLICATIONS"
#define STORAGEUG_STR_APP_LOC_NOTICE \
	"IDS_ST_BODY_SET_THE_DEFAULT_LOCATION_FOR_INSTALLING_APPLICATIONS_MSG"


/* For miscellaneous file view */
#define STORAGEUG_STR_N_SELECTED "IDS_ST_HEADER_PD_SELECTED_ABB"
#define STORAGEUG_STR_NO_SELECTED "IDS_ST_POP_NO_ITEM_SELECTED"


#endif /*__SETTING_STORAGE_STRING_H__ */
