/*
 * setting
 *
 * Copyright (c) 2000 - 2011 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#ifndef __SETTING_APPMGR_STRING_H__
#define __SETTING_APPMGR_STRING_H__

#define APPMGRUG_MAX_STR_LEN 64

/*system string */
#define MGRAPP_STR_ERROR "IDS_ST_POP_ERROR"
#define MGRAPP_STR_CANCEL "IDS_ST_BUTTON_CANCEL_ABB"
#define MGRAPP_STR_SIZE "IDS_ST_BODY_SIZE"
#define MGRAPP_STR_SORT_BY "IDS_ST_HEADER_SORT_BY"
#define MGRAPP_STR_ALL "IDS_ST_BODY_ALL"
#define MGRAPP_STR_BACK "IDS_ST_BUTTON_BACK"
#define MGRAPP_STR_OK "IDS_ST_BUTTON_OK"
#define MGRAPP_STR_STOP "IDS_ST_BUTTON_STOP"


/*package string */
#define MGRAPP_STR_RUNNING "IDS_ST_BODY_RUNNING"
#define MGRAPP_STR_DOWNLOADS "IDS_ST_BODY_DOWNLOADS"
#define MGRAPP_STR_CLEAR_DEFAULT_APPS "IDS_ST_BUTTON_REMOVE_DEFAULT_APPS_ABB"
#define MGRAPP_STR_CLEAR_DEFAULT_APPS_Q "IDS_ST_POP_REMOVE_DEFAULT_APPS_Q"

/*#define MGRAPP_STR_APP_MANAGER "IDS_ST_BODY_APPLICATION_MANAGER" */
#define MGRAPP_STR_APP_MANAGER "IDS_ST_BODY_APPLICATION_MANAGER"
#define MGRAPP_STR_UNINSTALLING "IDS_ST_POP_UNINSTALLING_ING"
#define MGRAPP_STR_UNINSTALL "IDS_ST_BUTTON_UNINSTALL"
#define MGRAPP_STR_KB "IDS_ST_BODY_KB"
#define MGRAPP_STR_MB "IDS_ST_BODY_MB"
#define MGRAPP_STR_GB "IDS_ST_BODY_GB"
#define MGRAPP_STR_TOTAL "IDS_ST_BODY_TOTAL"
#define MGRAPP_STR_APPLICATION "IDS_ST_BODY_APPLICATION"
#define MGRAPP_STR_DATA "IDS_ST_BODY_DATA"
#define MGRAPP_STR_CLEAR_DEFAULTS "IDS_ST_BODY_CLEAR_DEFAULTS"
#define MGRAPP_STR_DEFAULT_DESC "IDS_ST_BODY_YOU_HAVE_SELECTED_TO_LAUNCH_THIS_APPLICATION_BY_DEFAULT_FOR_SOME_ACTIONS"
#define MGRAPP_STR_STORAGE "IDS_ST_BODY_STORAGE"
#define MGRAPP_STR_LAUNCH_BY_DEFAULT "IDS_ST_BODY_LAUNCH_BY_DEFAULT"

#define MGRAPP_STR_RESET_APPS "IDS_ST_BUTTON_RESET_APPS_ABB"

#define MGRAPP_STR_A_TO_Z "IDS_MF_OPT_NAME_HA_TO_Z"
#define MGRAPP_STR_Z_TO_A "IDS_MF_OPT_NAME_HZ_TO_A"

#define MGRAPP_STR_APPLICATION_INFO "IDS_ST_BODY_APPLICATION_INFO"
#define MGRAPP_STR_MOVE_TO_SD "IDS_ST_BUTTON_MOVE_TO_SD_ABB"
#define MGRAPP_STR_MOVE_TO_PHONE "IDS_ST_BUTTON_MOVE_TO_PHONE"
#define MGRAPP_STR_SD_FULL "IDS_MSGC_POP_YOUR_SD_CARD_IS_FULL"
#define MGRAPP_STR_MOVE_FAIL "IDS_EMAIL_POP_FAILED_TO_MOVE"
#define MGRAPP_STR_NO_MEM "IDS_MSGC_BODY_NOT_ENOUGH_MEMORY_IN_PHONE_MEMORY_DELETE_SOME_ITEMS_AND_TRY_AGAIN"
#define MGRAPP_STR_MOVEING "IDS_PB_BODY_MOVING_ING"
#define MGRAPP_STR_UNINSTALL_MSG "IDS_ST_POP_UNINSTALL_Q"
#define MGRAPP_STR_UNINSTALL_COMPLETE "IDS_ST_POP_THE_APP_HAS_BEEN_UNINSTALLED"
#define MGRAPP_STR_UNINSTALL_FAILED "IDS_ST_POP_FAILED_TO_UNINSTALL_THE_APP"
#define MGRAPP_STR_APP_STOP_MSG "IDS_ST_BODY_THE_APPLICATIONS_BELOW_WERE_STARTED_BY_PS_STOPPING_THESE_APPLICATIONS_MAY_CAUSE_PS_TO_FAIL"
#define MAGAPP_STR_WEB_SETTING "IDS_BR_BODY_WEBSITE_SETTINGS"
#define MGRAPP_STR_PRIVILEGE "IDS_ST_HEADER_PRIVILEGES"
#define MGRAPP_STR_MOVE_COMPLETED "IDS_PB_POP_MOVE_COMPLETED"
#define MGRAPP_STR_UNINSTALL_UPDATES "IDS_ST_BUTTON_UNINSTALL_UPDATES"

#define MGRAPP_STR_FORCE_STOP "IDS_ST_BUTTON_FORCE_STOP"
#define MGRAPP_STR_ENABLE "IDS_ST_BUTTON_ENABLE"
#define MGRAPP_STR_DISABLE "IDS_ST_BUTTON_DISABLE"
#define MGRAPP_STR_DISABLED "IDS_ST_SBODY_DISABLED"

#define MGRAPP_STR_ACTIVE_APP "IDS_ST_MBODY_ACTIVE_APPLICATION"
#define MGRAPP_STR_ACTIVE_APPS_N "IDS_TASKMGR_BODY_ACTIVE_APPLICATIONS_C_PD"
#define MGRAPP_STR_APPS "IDS_ST_BODY_APPLICATIONS"
#define MGRAPP_STR_VERSION_STR "IDS_ST_BODY_VERSION_PS"
#define MGRAPP_STR_COMPUTING "IDS_ST_BODY_COMPUTING_ING"
#define MGRAPP_STR_NO_APPS "IDS_FP_BODY_NO_APPLICATIONS"
#define MGRAPP_STR_NO_DOWNLOAD_APPS_HELP "IDS_ST_BODY_AFTER_YOU_DOWNLOAD_AND_INSTALL_APPLICATIONS_APPLICATIONS_WILL_BE_SHOWN_HERE"
#define MGRAPP_STR_NO_RUNNING_APP "IDS_TASK_BODY_NO_RUNNING_APPLICATION"
#define MGRAPP_STR_CHECKING "IDS_COM_POP_CHECKING"
#define MGRAPP_STR_LOADING "IDS_ST_POP_LOADING_ING"

#define MGRAPP_STR_CACHE "IDS_ST_BODY_CACHE"
#define MGRAPP_STR_CLEAR_CACHE "IDS_TASKMGR_BUTTON_CLEAR_CACHE"

#endif /*__SETTING_APPMGR_STRING_H__ */
